call plug#begin('~/.vim/plugged/')
Plug 'https://github.com/vim-airline/vim-airline.git'
Plug 'https://github.com/vim-airline/vim-airline-themes.git'
Plug 'https://github.com/jiangmiao/auto-pairs.git'
Plug 'https://github.com/ap/vim-css-color.git'
Plug 'https://github.com/lervag/vimtex.git'
Plug 'https://github.com/preservim/nerdtree.git'
Plug 'https://github.com/neovimhaskell/haskell-vim.git'
call plug#end()
