add_newline = false

[line_break]
disabled = true

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 0
repo_root_style = "purple"
use_logical_path = false
format = "[$path]($style) "
repo_root_format = "[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($repo_root_style) "

[git_status]
ahead = "⇡ ${count}"
behind = "⇣${count}"
deleted = "x${count}"
untracked =	"?${count}"
modified = "!${count}"
staged = "+${count}"
diverged = "⇕⇡ ${ahead_count}⇣ ${behind_count}"
style = "bold red"

[git_branch]
symbol = " "
format = "on [$symbol$branch(:$remote_branch)]($style) "
style = "bold dimmed green"

[cmd_duration]
disabled = false
format = "[\\[$duration\\]]($style) "
min_time = 1

[package]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[c]
disabled = true

[conda]
disabled = true

[dart]
disabled = true

[docker_context]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true
