
[colors.primary]
background = "#1e222a"
foreground = "#f8f8f2"

[colors.normal]
black   = "#000000"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#bfbfbf"

[colors.bright]
black   = "#4d4d4d"
red     = "#ff6e67"
green   = "#5af78e"
yellow  = "#f4f99d"
blue    = "#caa9fa"
magenta = "#ff92d0"
cyan    = "#9aedfe"
white   = "#e6e6e6"

[colors.cursor]
cursor = "#c7ccd1"
text = "#1c2023"

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor]
vi_mode_style = "Block"

[font]
size = 16.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

