# Alacritty configuration (TOML format)
[window]
dimensions = { columns = 180, lines = 35 }

[font]
size = 16

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[cursor]
[cursor.style]
shape = "Block"
blinking = "Off"

[cursor.vi_mode_style]
shape = "Block"


[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
